---
title: "Welcome to my Portfolio!"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hi, my name is Troy Ascher. I'm currently doing a master's degree from in Computer Information Systems with a Business Intelligence and Database Management specialization at Boston University. I'll graduate in May of 2022 and I'm looking for a challenging and interseting job that involves data analysis and business intelligence. To assist employers with seeing my skillset I've built this website. Welcome!

I built this website using RStudio and used Github for hosting.

My portfolio has three main sections: R projects, Python projects, and SQL projects.

### R Projects

The R Projects highlight projects that I've done for school, projects that I've done for fun, and some assignments that I've done as I work through Wickham et al.'s R for Data Science.

### Python Projects

My python projects highlight projects that I've done for fun and or for school.

### SQL Projects

The SQL projects highlight the MS SQL Server projects that I've done as a part of my Master of Science program at Boston University.
