<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analysis of Beijing Weather and Pollution, 2017</title>

<script src="site_libs/header-attrs-2.9/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    RStudio
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="CS544_FinalProject_Ascher_Rmarkdown.html">Analytics Project for Boston University</a>
    </li>
    <li>
      <a href="Unemployment_API_Notebook.html">Working with APIs</a>
    </li>
    <li class="dropdown-header">ETL Example</li>
    <li class="dropdown-header">Sampling Methods</li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">R for Data Science Assignments</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="rfordatascience.html">Overview</a>
        </li>
        <li>
          <a href="rfdschapter5.html">Data Transformation - Ch 5</a>
        </li>
      </ul>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Python
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Doogie Howser Project</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    SQL
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Health and Wellness Tracker</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Resume
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Resume.html">Resume</a>
    </li>
    <li>
      <a href="aboutme.html">About me</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:&lt;ascher.troy@gmail.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/leetroyjenkins/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/troy-ascher/">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Analysis of Beijing Weather and Pollution, 2017</h1>

</div>


<pre class="r"><code># To create a tibble and manipulate the df that way.
library(tidyverse)

# Load this library for easily calculating the AQI. 
library(con2aqi)

# Open air allows windroses to be plotted.
library(openair)

# Color pallette &quot;WesAnderson&quot;
library(wesanderson)
wes.colors &lt;- names(wes_palettes)

# Color pallette to use instead of WesAnderson pallette
library(RColorBrewer)
colorbrew &lt;- row.names(RColorBrewer::brewer.pal.info)

# For using subplots
library(plotly)

# For strata sampling
library (sampling)</code></pre>
<div id="introduction" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Introduction</h1>
<div id="outline" class="section level2" number="1.1">
<h2 number="1.1"><span class="header-section-number">1.1</span> Outline</h2>
<p>This analysis is done on pollution and weather information in Beijing. This data was chosen to investigate sky conditions and the levels of pollutants in Beijing to see if there is correlation between meteorological conditions and the levels of pollution.</p>
<p>This presentation will:</p>
<ul>
<li><p>Introduce the datasets and the steps taken to transform the data.</p></li>
<li><p>Analyze sky conditions in Beijing.</p></li>
<li><p>Introduce and analyze AQI pollution levels in Beijing.</p></li>
<li><p>Test the Central Limit Theorem on the AQI data.</p></li>
<li><p>Compare the distribution of samples to the distribution of the population.</p></li>
<li><p>Analyze the relationship between wind speed, wind direction, and pollution.</p></li>
<li><p>Make recommendations for further analysis and conclude.</p></li>
</ul>
</div>
<div id="dataset" class="section level2" number="1.2">
<h2 number="1.2"><span class="header-section-number">1.2</span> Dataset</h2>
<pre class="r"><code>def.par &lt;- par()
scipen &lt;- 10
# Grabs the names of the CSV files. 
local.files &lt;-
  list.files(
    &quot;C:/Users/troya/OneDrive/R/CS544_FinalProject_Ascher/Datasets/Dataverse/&quot;
  )

local.dir &lt;-
  &quot;C:/Users/troya/OneDrive/R/CS544_FinalProject_Ascher/Datasets/Dataverse/&quot;


# Create variables names
var.names &lt;- paste(&quot;wd&quot;,local.files, sep = &quot;_&quot;)


 # Function for loading the files
grab.and.format &lt;-
  function(location, vec) {
    for (i in vec) {
      x &lt;-
        read.csv(
          paste(
            location,
            i,
            sep = &quot;&quot;
          ),
          header = TRUE
        )
      return(x)
    }
  }


# Create the files
for (i in seq(1, length(var.names))){
  assign(var.names[i], grab.and.format(local.dir, local.files[i]))
}

# Remove unnecessary objects.
remove(var.names)</code></pre>
<div id="source" class="section level3" number="1.2.1">
<h3 number="1.2.1"><span class="header-section-number">1.2.1</span> Source</h3>
<p>The data is from two data-sets from Harvard’s Dataverse in the form of a study by Wang (2019). The data was provided by the Ministry of Environmental Protection (MEP) of China and the National Oceanic and Atmospheric Administration (NOAA). The data-sets include 311010 hourly observations from pollution monitoring stations in Beijing, and 158047 hourly observations from pollution monitoring stations.</p>
<p>The observations included in the datasets are:</p>
<p>MEP (pollutant) data:</p>
<pre class="r"><code>for (i in names(wd_beijing_17_18_aq.csv)) {
  print(i)
}</code></pre>
<pre><code>## [1] &quot;stationId&quot;
## [1] &quot;utc_time&quot;
## [1] &quot;PM2.5&quot;
## [1] &quot;PM10&quot;
## [1] &quot;NO2&quot;
## [1] &quot;CO&quot;
## [1] &quot;O3&quot;
## [1] &quot;SO2&quot;</code></pre>
<p>NOAA (weather) data:</p>
<pre class="r"><code>for (i in names(wd_beijing_17_18_meo.csv)) {
  print(i)
}</code></pre>
<pre><code>## [1] &quot;station_id&quot;
## [1] &quot;longitude&quot;
## [1] &quot;latitude&quot;
## [1] &quot;utc_time&quot;
## [1] &quot;temperature&quot;
## [1] &quot;pressure&quot;
## [1] &quot;humidity&quot;
## [1] &quot;wind_direction&quot;
## [1] &quot;wind_speed&quot;
## [1] &quot;weather&quot;</code></pre>
</div>
<div id="data-manipulation" class="section level3" number="1.2.2">
<h3 number="1.2.2"><span class="header-section-number">1.2.2</span> Data Manipulation</h3>
<p>The following steps were taken to combine the data.</p>
<p>Merge datasets into one frame based on shared station Ids.</p>
<ol style="list-style-type: decimal">
<li><p>Combine datasets into one dataframe based on station Id</p>
<pre class="r"><code># Identify which stations are in each dataset by removing the suffix, merging
# the characters into two columns in a dataframe, and then checking which values
# are in each column.


# Format Dataframe station names so that they can be compared between lists and
# used as a key value when combined with date.
wd_beijing_17_18_aq.csv$stationId &lt;- substring(wd_beijing_17_18_aq.csv$stationId, 1, nchar(wd_beijing_17_18_aq.csv$stationId) - 3)

wd_beijing_17_18_meo.csv$station_id &lt;- substring(wd_beijing_17_18_meo.csv$station_id, 1, nchar(wd_beijing_17_18_meo.csv$station_id) - 4)


# Get the unique station names from each list.
aq.names &lt;- unique(wd_beijing_17_18_aq.csv$stationId)

meo.names &lt;- unique(wd_beijing_17_18_meo.csv$station_id)


# Merge unique names into a dataframe of two columns.
temp.names &lt;- merge(aq.names, meo.names)


# Identify which stations are in each dataset. Can use this as a key.
temp.names &lt;- subset(temp.names, temp.names$x == temp.names$y)


# Create new datasets of air and weather that only contain the stations that are
# in each dataset.
raw.air &lt;-
  subset(wd_beijing_17_18_aq.csv,
         wd_beijing_17_18_aq.csv$stationId %in% temp.names$x)
for (i in unique(raw.air$stationId)) {
  print(i)
}</code></pre>
<pre><code>## [1] &quot;daxing&quot;
## [1] &quot;fangshan&quot;
## [1] &quot;huairou&quot;
## [1] &quot;mentougou&quot;
## [1] &quot;miyun&quot;
## [1] &quot;pingchang&quot;
## [1] &quot;pinggu&quot;
## [1] &quot;shunyi&quot;
## [1] &quot;tongzhou&quot;</code></pre>
<pre class="r"><code>raw.meo &lt;-
  subset(wd_beijing_17_18_meo.csv,
         wd_beijing_17_18_meo.csv$station_id %in% temp.names$x)



# Remove the original dataframes and unnecessary objects.
remove(aq.names, meo.names, temp.names, i)


# Check that the unique values match.
# unique(raw.air$stationId) %in% unique(raw.meo$station_id)
# unique(raw.meo$station_id) %in% unique(raw.air$stationId)</code></pre></li>
<li><p>Delete data for stations that don’t exist in each data-set and remove any rows containing NA.</p>
<pre class="r"><code># Create a key value based on date and station name in each dataset.
raw.air$PKID &lt;- paste(raw.air$stationId, raw.air$utc_time, sep = &quot;_&quot;)
raw.meo$PKID &lt;-paste(raw.meo$station_id, raw.meo$utc_time, sep = &quot;_&quot;)


# Merge dataframes based on PKID.
raw.data &lt;- merge(raw.air, raw.meo, by=&quot;PKID&quot;)


# Remove unneeded dataframes, save the combined raw data.
remove(raw.air, raw.meo)


# Create a working dataframe with only columns needed and no NA values.
cn.atmos &lt;- subset(raw.data, select = -c(utc_time.y, station_id))

# Remove extreme values
cn.atmos$PM2.5[cn.atmos$wind_speed &gt; 30] &lt;- NA


# Remove NA values
paste(&quot;NA count before removal:&quot;,sum(is.na(cn.atmos$PM2.5)), sep = &quot; &quot;) # 3219</code></pre>
<pre><code>## [1] &quot;NA count before removal: 3220&quot;</code></pre>
<pre class="r"><code>cn.atmos &lt;- na.omit(cn.atmos)

paste(&quot;NA count after removal:&quot;,sum(is.na(cn.atmos$PM2.5)), sep = &quot; &quot;) # 0</code></pre>
<pre><code>## [1] &quot;NA count after removal: 0&quot;</code></pre></li>
<li><p>Use ‘con2air’ library to calculate the AQI based on pollutant levels for each reading.</p>
<pre class="r"><code># ------ The following section deals with formatting values in order to 
# ------ calculate the US EPA&#39;s AQI value based on measured pollutants.

# Units need to be converted to AQI for easier reading.
# Alter PM10 Values greater than 604 (EPA guidelines do not go that high) to the
# max value.

cn.atmos$PM10 &lt;- replace(cn.atmos$PM10, cn.atmos$PM10 &gt; 604, 604)  



# convert units from ug to MG Conversion formula from:
# https://cfpub.epa.gov/ncer_abstracts/index.cfm/fuseaction/display.files/fileid/14285
# https://www.teesing.com/en/page/library/tools/ppm-mg3-converter

cn.atmos$NO2 &lt;- (24.45 * cn.atmos$NO2 / 46.01)
cn.atmos$CO &lt;- 24.45 * cn.atmos$CO / 28.01
cn.atmos$O3 &lt;- (24.45 * cn.atmos$O3 / 48.00) / 1000
cn.atmos$SO2 &lt;-(24.45 * cn.atmos$SO2 / 64.06)


# Use con3aqi libary to convert values to US AQI standard.
cn.atmos$PM2.5 &lt;- con2aqi(pollutant=&quot;pm25&quot;,con=cn.atmos$PM2.5) # Works
cn.atmos$PM10 &lt;- con2aqi(pollutant=&quot;pm10&quot;,con=cn.atmos$PM10) # works

cn.atmos$O3 &lt;- con2aqi(pollutant=&quot;o3&quot;,con=cn.atmos$O3, type = &quot;1h&quot;)

cn.atmos$NO2 &lt;- con2aqi(pollutant=&quot;no2&quot;,con=cn.atmos$NO2) # Works
cn.atmos$CO &lt;- con2aqi(pollutant=&quot;co&quot;,con=cn.atmos$CO) # works
cn.atmos$SO2 &lt;- con2aqi(pollutant=&quot;so2&quot;,con=cn.atmos$SO2) # Works


 # Calculate AQI

count &lt;- 1
for (i in seq(0, length(cn.atmos$PKID) - 1)) {
  cn.atmos$AQI[count] &lt;-   max(c(
    cn.atmos$PM2.5[count],
    cn.atmos$PM10[count],
    cn.atmos$NO2[count],
    cn.atmos$CO[count],
    cn.atmos$O3[count],
    cn.atmos$SO2[count]
  ))
  count &lt;- count + 1
}</code></pre></li>
<li><p>Reformat date as UTC standard and add year, day, and month columns and convert units from metric to imperial.</p>
<pre class="r"><code># Create a chart of Latitude and Longitude for map use
cn.geo &lt;-
  unique(subset(cn.atmos,
         select =
           c(&quot;stationId&quot;, &quot;longitude&quot;, &quot;latitude&quot;)))


cn.atmos &lt;- subset(cn.atmos, select= -c(longitude, latitude))


# reformat the date column for use with the windrose
names(cn.atmos)[3] &lt;- &quot;date&quot;
cn.atmos$date &lt;- as.POSIXct(cn.atmos$date, tz = &quot;UTC&quot;)


# Convert temp to Farenheit
# (0°C × 9/5) + 32 = 32°F
cn.atmos$temperature &lt;- round((cn.atmos$temperature * 9/5) + 32)


# Convert wind speed to mph
cn.atmos$wind_speed &lt;- round(cn.atmos$wind_speed * 2.23694)


# Create date field for calculating values by day.
cn.atmos$day_date &lt;- substring(cn.atmos$date, 1, 10)

# Add decatenated date columns.
cn.atmos$year &lt;- str_sub(cn.atmos$day_date, start = 1, end = 4)
cn.atmos$month &lt;- str_sub(cn.atmos$day_date, start = 6, end = 7)
cn.atmos$day &lt;- str_sub(cn.atmos$day_date, start = 9, end = 10)</code></pre></li>
<li><p>Add columns with AQI warning messaging and colors as defined by the EPA.</p>
<pre class="r"><code># Create AQI Colors and levels according to EPA guidelines.
aqi.col &lt;- c(&quot;Green&quot;, &quot;Yellow&quot;, &quot;Orange&quot;, &quot;Red&quot;, &quot;Purple&quot;, &quot;Maroon&quot;)

aqi.range.high &lt;- c(50,
               100,
               150,
               200,
               300,
               500)

aqi.range.low &lt;- c(0, 51, 101, 151, 201, 301)

aqi.html &lt;- c(&quot;#00e400&quot;,
  &quot;#ffff00&quot;,
  &quot;#ff7e00&quot;,
  &quot;#ff0000&quot;,
  &quot;#8f3f97&quot;,
  &quot;#7e0023&quot;)

col.r &lt;- c(0, 255, 255, 255, 143, 126)
col_g &lt;- c(228, 255, 126, 0, 63, 0)
col.b &lt;- c(0, 0, 0, 0, 151, 35)
aqi.message &lt;- c(
  &quot;Good&quot;,
  &quot;Moderate&quot;,
  &quot;Unhealthy for Some&quot;,
  &quot;Unhealthy&quot;,
  &quot;Very Unhealthy&quot;,
  &quot;Hazardous&quot;
)


aqi.guide &lt;- data.frame(
  Color = aqi.col,
  Low = aqi.range.low,
  High = aqi.range.high,
  HTML = aqi.html,
  Message = aqi.message
)


# Remove unnecessary objects.
remove(
  aqi.col,
  aqi.message,
  aqi.range.high,
  aqi.range.low,
  col.b,
  col.r,
  col_g,
  aqi.html
)

aqi.level &lt;- function(n){
  if (n &lt;= 51){
    return(&quot;Good&quot;)
  } else if (n &lt;= 101){
    return(&quot;Moderate&quot;)
  } else if (n &lt;= 151){
    return(&quot;Unhealthy for Some&quot;)
  } else if(n &lt;= 201){
    return(&quot;Unhealthy&quot;)
  } else if(n &lt;= 301){
    return(&quot;Very Unhealthy&quot;)
  } else if (n &gt; 300){
    return(&quot;Hazardous&quot;)
  }
      }

# Create a new column to calculate the AQI level messaging in. 
cn.atmos$aqi_level &lt;- cn.atmos$AQI

for (i in seq(1, length(cn.atmos$AQI))) {
  cn.atmos$aqi_level[i] &lt;- aqi.level(cn.atmos$AQI[i])
}</code></pre></li>
<li><p>Turn dataframe into a Tibble.</p>
<pre class="r"><code># Turn DF into a tibble object to make analysis easier. 
cn.atmos.backup &lt;- cn.atmos

cn.atmos &lt;- as_tibble(cn.atmos)</code></pre></li>
<li><p>Remove data for 2018 because it is incomplete.</p>
<pre class="r"><code># Remove data for 2018.
cn.atmos &lt;- subset(cn.atmos, cn.atmos$year == 2017)</code></pre></li>
<li><p>Create season columns</p>
<pre class="r"><code># Remove data for 2018.
cn.atmos &lt;- subset(cn.atmos, cn.atmos$year == 2017)


# Create a seasons column and calculate the season based on the month column.
cn.atmos$season &lt;- as.integer(str_sub(cn.atmos$day_date, start = 6, end = 7))


# Create vector of seasons to look up. 
seasons &lt;-
  c(
    &quot;Winter&quot;,
    &quot;Winter&quot;,
    &quot;Spring&quot;,
    &quot;Spring&quot;,
    &quot;Spring&quot;,
    &quot;Summer&quot;,
    &quot;Summer&quot;,
    &quot;Summer&quot;,
    &quot;Fall&quot;,
    &quot;Fall&quot;,
    &quot;Fall&quot;,
    &quot;Winter&quot;
  )


# Calculate seasons based on month.
cn.atmos$season &lt;- seasons[cn.atmos$season]



# Change &quot;Sunny/clear&quot; to &quot;Sunny&quot; for clarity and ease with plotting.
cn.atmos$weather[cn.atmos$weather == &quot;Sunny/clear&quot;] &lt;- &quot;Clear&quot;

#Change AQI to double to use in calculations.
cn.atmos$AQI &lt;- as.double(cn.atmos$AQI)</code></pre></li>
<li><p>The final tibble.</p>
<pre class="r"><code>head(cn.atmos)</code></pre>
<pre><code>## # A tibble: 6 x 22
##   PKID         stationId date                PM2.5  PM10   NO2    CO    O3   SO2
##   &lt;chr&gt;        &lt;chr&gt;     &lt;dttm&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 daxing_2017~ daxing    2017-01-30 16:00:00   179    84    16    13    61    20
## 2 daxing_2017~ daxing    2017-01-30 17:00:00   183    88    17    14    60    28
## 3 daxing_2017~ daxing    2017-01-30 18:00:00   184    86    16    15    60    30
## 4 daxing_2017~ daxing    2017-01-30 19:00:00   187    88    17    16    59    27
## 5 daxing_2017~ daxing    2017-01-30 22:00:00   186    85    15    18    58    16
## 6 daxing_2017~ daxing    2017-01-30 23:00:00   188    87    20    18    56    16
## # ... with 13 more variables: temperature &lt;dbl&gt;, pressure &lt;dbl&gt;,
## #   humidity &lt;int&gt;, wind_direction &lt;dbl&gt;, wind_speed &lt;dbl&gt;, weather &lt;chr&gt;,
## #   AQI &lt;dbl&gt;, day_date &lt;chr&gt;, year &lt;chr&gt;, month &lt;chr&gt;, day &lt;chr&gt;,
## #   aqi_level &lt;chr&gt;, season &lt;chr&gt;</code></pre></li>
</ol>
</div>
</div>
</div>
<div id="analysis" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> Analysis</h1>
<div id="sky-conditions" class="section level2" number="2.1">
<h2 number="2.1"><span class="header-section-number">2.1</span> Sky Conditions</h2>
<p>Initial analysis of the data shows that there are seven unique conditions recorded by the NOAA over the one year observation period.</p>
<pre class="r"><code># Table of weather conditions.
cn.atmos$weather %&gt;% table()</code></pre>
<pre><code>## .
## Clear  Dust   Fog  Haze  Rain  Sand  Snow 
## 34778     1  2422  8946   197     4    24</code></pre>
<pre class="r"><code># Barplot of Weather condition. 

weather.tb &lt;- cn.atmos$weather %&gt;% table()
weather.bp &lt;- weather.tb %&gt;% barplot(
  las = 1 ,
  col = brewer.pal(n=7, &quot;PuBu&quot;),
    #wes_palette(wes.colors[14], 7, type = &quot;continuous&quot;),
  ylim = c(0, 40000),
  main = &quot;Recorded Sky Conditions in Beijing&quot;,
  sub = &quot;Across nine weather stations&quot;
)
text(x = weather.bp, y = weather.tb, label = weather.tb, pos = 3)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/sky-conditions-1.png" width="672" /></p>
<p>The bar-chart above indicates that four of the seven sky conditions are rarely observed. Looking at the proportions we can see that dust, rain, sand and snow make up less than 1% of the total observations. It makes sense that rain and snow is infrequent since Beijing’s climate is considered a “high-desert”.</p>
<pre class="r"><code>round(sky.cond.pt, 3)</code></pre>
<pre><code>## .
##  Clear   Dust    Fog   Haze   Rain   Sand   Snow 
## 74.998  0.002  5.223 19.292  0.425  0.009  0.052</code></pre>
<p>Taking this into account, a new bar-plot is plotted with only the weather observations whose frequency is greater than 1%.</p>
<pre class="r"><code># Calculate the frequency of each weather condition across all observations.
weather.df &lt;- data.frame(table(cn.atmos$weather))
weather.df$percent &lt;- weather.df$Freq / sum(weather.df$Freq) * 100

# Barchart where occurence is greater than 1%.

par(mar = c(5,5,2,1))

weather.df2 &lt;- subset(weather.df, weather.df$percent &gt; 1)

par(mfrow = c(1,2))
weather.bp2 &lt;- barplot(
  height = subset(weather.df$Freq, weather.df$percent &gt; 1),
  names.arg = subset(weather.df$Var1, weather.df$percent &gt; 1),
  horiz = TRUE,
  las = 1,
  xlim = c(0,40000),
  main = &quot;Count of cloudy, clear, and hazy days.&quot;,
  sub = &quot;where % is &gt; 1&quot;,
  xlab = &quot;Frequency of Conditions&quot;,
  col = rev(brewer.pal(n=3, &quot;PuBu&quot;))
    #wes_palette(wes.colors[19], 3, type = &quot;discrete&quot;)
)
legend(x = &quot;topright&quot;,
       title = &quot;Count&quot;,
       legend = rev(weather.df2$Freq), 
       fill = rev(brewer.pal(n=3, &quot;PuBu&quot;))
         #rev(wes_palette(wes.colors[16], 3, type = &quot;discrete&quot;))
       )
par(mar = c(2,2,1,0))
subset(weather.df$Freq, weather.df$percent &gt; 1) %&gt;%
  pie(
    labels = paste(round(
      subset(weather.df$percent, weather.df$percent &gt; 1)
    ), &quot;%&quot;, sep = &quot;&quot;),
    col = rev(brewer.pal(n=3, &quot;PuBu&quot;)),
      #wes_palette(wes.colors[16], 3, type = &quot;discrete&quot;),
    main = &quot;% of sky conditions.&quot;
  )
legend(
  x = &#39;topleft&#39;,
  legend = subset(weather.df$Var1, weather.df$percent &gt; 1),
  fill =  brewer.pal(n=3, &quot;PuBu&quot;)
    #wes_palette(wes.colors[16], 3, type = &quot;discrete&quot;)
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/barchart-of-significant-weather-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>Next, weather conditions are compared by season to see what seasonal differences occur.</p>
<pre class="r"><code># by season

par(oma = c(3,0,3,2))
par(mar = c(3,5,2,0))
par(mfrow = c(2, 2))


for (i in unique(cn.atmos$season)){
  barplot(
    height = table(subset(cn.atmos$weather, cn.atmos$season == i)),
    xlim = c(0, 14000),
    horiz = TRUE,
    beside = TRUE,
    # main = i,
    las = 2,
    col = rev(brewer.pal(n=5, &quot;PuBu&quot;)),
      #wes_palette(wes.colors[2], 5, type = &quot;discrete&quot;),
    main = i
  )
  legend(x = &quot;topright&quot;,
         title = &quot;Count&quot;,
         legend = table(subset(cn.atmos$weather, cn.atmos$season == i)), 
         fill = rev(brewer.pal(n=5, &quot;PuBu&quot;)),
           #wes_palette(wes.colors[2], 5, type = &quot;discrete&quot;),
         cex = .7
  )
}
mtext(&quot;Sky Conditions&quot;,outer = TRUE, side = 1, line = 1)
mtext(&quot;Sky Conditions by occurence, by season&quot;, side = 3, line = 1, cex = 1.5, outer = TRUE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/sky-conditions-by-season-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>This data shows that Fall and Summer have the highest count of Clear observations. Snow only occurs during the winter, and Fog has a much higher occurrence during the summer and fall then during the winter or spring. What if we only look at days that are not clear?</p>
<pre class="r"><code>par(oma = c(3,0,3,2))
par(mar = c(3,5,2,0))
par(mfrow = c(2, 2))


for (i in unique(cn.atmos$season)){
  barplot(
    height = table(subset(cn.atmos$weather, cn.atmos$season == i &amp; !cn.atmos$weather == &#39;Clear&#39;)),
    xlim = c(0, 3000),
    horiz = TRUE,
    beside = TRUE,
    # main = i,
    las = 2,
    col = rev(brewer.pal(n=4, &quot;PuBu&quot;)),
      #wes_palette(wes.colors[2], 5, type = &quot;discrete&quot;),
    main = i
  )
  legend(x = &quot;topright&quot;,
         title = &quot;Count&quot;,
         legend = table(subset(cn.atmos$weather, cn.atmos$season == i &amp; !cn.atmos$weather == &#39;Clear&#39;)), 
         fill = rev(brewer.pal(n=4, &quot;PuBu&quot;)),
           #wes_palette(wes.colors[2], 5, type = &quot;discrete&quot;),
         cex = .7
  )
}
mtext(&quot;Beijing Sky Conditions&quot;,outer = TRUE, side = 1, line = 1)
mtext(&quot;Beijing Sky Conditions by occurence, by season, excluding Clear days&quot;, side = 3, line = 1, cex = 1.5, outer = TRUE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/conditions-by-season-excluding-clear-days-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>These plots demonstrate that other than clear days haze is the condition that most often occurs in Beijing throughout the year.</p>
</div>
<div id="analysis-on-aqi" class="section level2" number="2.2">
<h2 number="2.2"><span class="header-section-number">2.2</span> Analysis on AQI</h2>
<div id="what-is-aqi" class="section level3" number="2.2.1">
<h3 number="2.2.1"><span class="header-section-number">2.2.1</span> What is AQI?</h3>
<p>The Air Quality Index (AQI) is the Environmental Protection Agency’s (EPA) index on air quality. It takes the measurement for six common pollutants and calculates a index based on the levels of the pollutants (AirNow.gov, n.d.).</p>
<p>The pollutants are:</p>
<ul>
<li><p>Ozone (O3)</p></li>
<li><p>Very Small Particle Matter (PM2.5)</p></li>
<li><p>Particle Matter (PM10)</p></li>
<li><p>Carbon Monoxide (CO)</p></li>
<li><p>Sulfur Dioxide ( )</p></li>
<li><p>Nitrogen Dioxide (NO2)</p></li>
</ul>
<p>Based on the AQI value, the EPA assigns the air quality into a category from ‘Good’ to ‘Hazardous’.</p>
<pre class="r"><code>print.data.frame(aqi.guide[c(&quot;Message&quot;, &quot;Low&quot;, &quot;High&quot;, &quot;Color&quot; )])</code></pre>
<pre><code>##              Message Low High  Color
## 1               Good   0   50  Green
## 2           Moderate  51  100 Yellow
## 3 Unhealthy for Some 101  150 Orange
## 4          Unhealthy 151  200    Red
## 5     Very Unhealthy 201  300 Purple
## 6          Hazardous 301  500 Maroon</code></pre>
</div>
<div id="aqi-counts" class="section level3" number="2.2.2">
<h3 number="2.2.2"><span class="header-section-number">2.2.2</span> AQI Counts</h3>
<p>The following table shows a count of the AQI levels by category across all observations and a histogram of the distribution.</p>
<pre class="r"><code>table(cn.atmos$aqi_level)</code></pre>
<pre><code>## 
##          Hazardous           Moderate          Unhealthy Unhealthy for Some 
##                156              23525              13584               7779 
##     Very Unhealthy 
##               1328</code></pre>
<pre class="r"><code>par(mar = c(5.1,5.1,2.1,2.1))
hist(
  cn.atmos$AQI,
  main = &quot;Counts of AQI, as distribution&quot;,
  xlim = c(0, 500),
  ylim = c(0, 30000),
  breaks = 10,
  las = 2, 
  axes = FALSE,
  xlab = &quot;AQI&quot;,
  labels = TRUE,
  ylab = &quot;Frequency&quot;,
  col = c(
    &quot;#ffff00&quot;,
    &quot;#ff7e00&quot;,
    &quot;#ff0000&quot;,
    &quot;#8f3f97&quot;,
    &quot;#8f3f97&quot;,
    &quot;#7e0023&quot;,
    &quot;#7e0023&quot;,
    &quot;#7e0023&quot;,
    &quot;#7e0023&quot;
  )
)
axis(1, at = c(seq(0, 500, 50)))
axis(2,
     at = c(seq(0, 30000, 5000)),
     las = 2,
     labels = c(0, paste(c(5, 10, 15, 20, 25, 30), &quot;k&quot;, sep = &quot;&quot;)))
legend(x = &quot;topright&quot;,
       aqi.guide$Message,
       fill = aqi.guide$HTML,
       cex = .6)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/hist-of-aqi-levels-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>The distribution is it positively skewed with the majority of the observations in the “Moderate” range between 50 and 100. The second observation is that there is never a US AQI level that is less than 50 in this data-set. This is concerning to me but is not surprising given the reputation that China has as a global producer of goods that uses coal as it’s main source of energy and taking into account that the amount of coal they burned increased slightly in 2017 (Reuters Staff, 2017).</p>
</div>
</div>
<div id="aqi-distribution" class="section level2" number="2.3">
<h2 number="2.3"><span class="header-section-number">2.3</span> AQI Distribution</h2>
<p>Using the summary function shows that the mean of all of the AQI values is 114.2. It also shows that the max value is 500, which is the max value allowed on the US AQI scale. While the spread between the Max and the Min values is 448, the difference between the 3rd quartile and the 1st quartile is is less than 100. In addition, the difference between the 3rd quartile and the Min value is 155. This reinforces that the data is positively skewed.</p>
<pre class="r"><code>summary(cn.atmos$AQI)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    52.0    68.0   100.0   114.2   157.0   500.0</code></pre>
<p>Weather and pollutants are affected by seasonal and business cycles. Comparing the population against the seasonal distributions shows that the spring months have the highest median, while the winter months have the most outliers to the right, but the lowest median. From this we can infer that during the spring in Beijing of 2017 the AQI was consistently higher, but the winter will had more extreme fluctuations.</p>
<pre class="r"><code>boxplot(cn.atmos$AQI,
        subset(cn.atmos$AQI, cn.atmos$season == &quot;Summer&quot;),
        subset(cn.atmos$AQI, cn.atmos$season == &quot;Fall&quot;),
        subset(cn.atmos$AQI, cn.atmos$season == &quot;Winter&quot;),
        subset(cn.atmos$AQI, cn.atmos$season == &quot;Spring&quot;),
        horizontal = TRUE,
        names = c(&quot;2017&quot;, &quot;Summer&quot;, &quot;Fall&quot;, &quot;Winter&quot;, &quot;Spring&quot;),
        las = 1,
        main = &quot;Boxplots of AQI, by season.&quot;,
        col = #rev(brewer.pal(n=5, &quot;PuBu&quot;))
          wes_palette(wes.colors[7], 5, type = &quot;continuous&quot;)
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/aqi-seasonal-distribution-1.png" width="672" /></p>
<p>Further deconstruction of the data into monthly sets allows us to see that February and December had the most outlier to the right. While January had no outliers, but the highest median. The two groups of March, April, and May, as well as October, November, and December have a fairly close distribution, respectively. It’s possible that factors that effect AQI such as climate, traffic, or business cycles remained the same during these periods.</p>
<pre class="r"><code>boxplot(
  subset(cn.atmos$AQI, cn.atmos$month == &quot;01&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;02&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;03&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;04&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;05&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;06&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;07&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;08&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;09&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;10&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;11&quot;),
  subset(cn.atmos$AQI, cn.atmos$month == &quot;12&quot;),
  horizontal = TRUE,
  names = c(
    &quot;Jan&quot;,
    &quot;Feb&quot;,
    &quot;Mar&quot;,
    &quot;Apr&quot;,
    &quot;May&quot;,
    &quot;Jun&quot;,
    &quot;Jul&quot;,
    &quot;Aug&quot;,
    &quot;Sep&quot;,
    &quot;Oct&quot;,
    &quot;Nov&quot;,
    &quot;Dec&quot;
  ),
  col = rev(brewer.pal(n=12, &quot;Set3&quot;)),
    #wes_palette(wes.colors[7], 12, type = &quot;continuous&quot;),
  las = 1,
  main = &quot;Boxplots of AQI, by season.&quot;
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/aqi-monthly-distribution-1.png" width="672" /></p>
</div>
<div id="aqi-pollutant-distribution" class="section level2" number="2.4">
<h2 number="2.4"><span class="header-section-number">2.4</span> AQI &amp; Pollutant Distribution</h2>
<p>The distribution of AQI can be compared with the distribution of the pollutants measured in the dataset.</p>
<pre class="r"><code>boxplot(
  cn.atmos$PM2.5,
  cn.atmos$PM10,
  cn.atmos$NO2,
  cn.atmos$CO,
  cn.atmos$O3,
  cn.atmos$SO2,
  cn.atmos$AQI,
  horizontal = TRUE,
  col = rev(brewer.pal(n=7, &quot;Set3&quot;)), 
    #rev(wes_palette(wes.colors[8], 7, type = &quot;continuous&quot;)),
  names = c(&quot;PM2.5&quot;, &quot;PM10&quot;, &quot;NO2&quot;, &quot;CO&quot;, &quot;O3&quot;, &quot;SO2&quot;, &quot;AQI&quot;),
  las = 1,
  main = &quot;Boxplots of Air Pollutants&quot;,
  xlab = &quot;Pollutant Concentration&quot;
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/aqi-and-pollutant-distribution-year-1.png" width="672" /></p>
<p>One observation is that the distribution of the AQI and PM2.5 are similar. An assertion could be made that there is correlation between AQI and PM2.5.</p>
</div>
<div id="distribution-by-season" class="section level2" number="2.5">
<h2 number="2.5"><span class="header-section-number">2.5</span> Distribution by Season</h2>
<pre class="r"><code>par(oma=c(3,3,3,3))
par(mfrow = c(2,2))
par(mar = c(2,4,2,1))
for (i in unique(cn.atmos$season)){
  boxplot(
    subset(cn.atmos$AQI, cn.atmos$season == i),
    subset(cn.atmos$PM2.5, cn.atmos$season == i),
    subset(cn.atmos$PM10, cn.atmos$season == i),
    subset(cn.atmos$NO2, cn.atmos$season == i),
    subset(cn.atmos$CO, cn.atmos$season == i),
    subset(cn.atmos$O3, cn.atmos$season == i),
    subset(cn.atmos$SO2, cn.atmos$season == i),
    horizontal = TRUE,
    col = rev(brewer.pal(n=7, &quot;Set3&quot;)),
      #rev(wes_palette(wes.colors[8], 7, type = &quot;continuous&quot;)),
    names = c(&quot;AQI&quot;, &quot;PM2.5&quot;, &quot;PM10&quot;, &quot;NO2&quot;, &quot;CO&quot;, &quot;O3&quot;, &quot;SO2&quot;),
    las = 1,
    main = i
  )
}
mtext(&quot;Pollutant Concentration&quot;,outer = TRUE, side = 1, line = 1)
mtext(&quot;Levels of pollutants, by season&quot;, side = 3, line = 1, cex = 1.5, outer = TRUE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/aqi-and-pollutant-by-season-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>Parsing the data by season reveals that PM2.5 and AQI have a similar distribution throughout the year.</p>
<div id="aqi-and-correlation-with-pollutants" class="section level3" number="2.5.1">
<h3 number="2.5.1"><span class="header-section-number">2.5.1</span> AQI and Correlation with Pollutants</h3>
<p>Examining the relationship between the pollutant variables and AQI by using Pearson’s correlation coefficient returns a value of 0.969 for AQI to PM2.5. This indicates correlation.</p>
<pre class="r"><code>cor(cn.atmos$AQI, cn.atmos$PM2.5, method = &quot;pearson&quot;)
cor(cn.atmos$AQI, cn.atmos$PM10, method = &quot;pearson&quot;)
cor(cn.atmos$AQI, cn.atmos$NO2, method = &quot;pearson&quot;)
cor(cn.atmos$AQI, cn.atmos$CO, method = &quot;pearson&quot;)
cor(cn.atmos$AQI, cn.atmos$O3, method = &quot;pearson&quot;)
cor(cn.atmos$AQI, cn.atmos$SO2, method = &quot;pearson&quot;)</code></pre>
<table>
<tbody>
<tr class="odd">
<td align="center"><sup><strong>Correlation Table</strong></sup></td>
<td align="center">AQI</td>
</tr>
<tr class="even">
<td align="center">PM2.5</td>
<td align="center">0.969</td>
</tr>
<tr class="odd">
<td align="center">PM10</td>
<td align="center">0.842</td>
</tr>
<tr class="even">
<td align="center">NO2</td>
<td align="center">0.547</td>
</tr>
<tr class="odd">
<td align="center">CO</td>
<td align="center">0.672</td>
</tr>
<tr class="even">
<td align="center">O3</td>
<td align="center">0.059</td>
</tr>
<tr class="odd">
<td align="center">SO2</td>
<td align="center">0.511</td>
</tr>
</tbody>
</table>
<p>Viewing the data graphically, the linear upward-right trend line is fairly obvious. Although correlation is not causation, because AQI is derived from a combination of the six pollutants we can accurately observe that PM2.5 has a strong effect on the AQI level. The red linear model line generally follows the shape of the plot.</p>
<pre class="r"><code># Plot of PM and AQI
par(def.par)
par(oma=c(3,3,3,3), mar = c(3,4,1,1))

plot(cn.atmos$AQI, 
     cn.atmos$PM2.5, 
     pch = 20,
     col = wes_palette(wes.colors[7], 1, type = &quot;continuous&quot;),
     xlab = &quot;&quot;,
     ylab = &quot;PM2.5&quot;,
     las = 1
)
abline(lm(cn.atmos$AQI ~ cn.atmos$PM2.5), col = &quot;red&quot;)
mtext(&quot;AQI&quot;,outer = TRUE, side = 1, line = 1)
mtext(&quot;Plot of AQI and PM2.5 levels&quot;, side = 3, line = 1, cex = 1.5, outer = TRUE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/plots-aqi-to-pm-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
</div>
</div>
<div id="aqi-and-the-central-limit-theorem" class="section level2" number="2.6">
<h2 number="2.6"><span class="header-section-number">2.6</span> AQI and the Central Limit Theorem</h2>
<p>The central limit theorem says that when many samples are taken that the means of the sample will be normally distributed around the mean. As more trials are run, the mean of the distribution will become closer to the mean of the population (University of California, Berkeley, n.d.).</p>
<table>
<thead>
<tr class="header">
<th align="center">Population Mean</th>
<th align="center">Population Standard Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">114.215</td>
<td align="center">50.4</td>
</tr>
</tbody>
</table>
<pre class="r"><code>aqi.mean &lt;- mean(cn.atmos$AQI)

aqi.sd &lt;- sd(cn.atmos$AQI)


set.seed(4099)


#Function for sampling
sample.and.mean &lt;- function (x, sample.size, reps) {
  temp.sample &lt;- seq(1:reps)
  xbar &lt;- numeric(reps)
  set.seed(4099)
  for (i in temp.sample) {
    xbar[i] &lt;- mean(sample(x, size = sample.size, replace = FALSE))
  }
  return(xbar)
}
par(mfrow = c(2,2), oma = c(2,2,3,0), mar = c(4,3,1,0))

four.samples &lt;- c(10, 20, 50, 500)
for (i in four.samples) {
  xbar &lt;- sample.and.mean(cn.atmos$AQI, i, 1000)
  assign(paste(&quot;aqi.mean&quot;, i, sep = &quot;_&quot;), mean(xbar))
  assign(paste(&quot;aqi.sd&quot;, i, sep = &quot;_&quot;), sd(xbar))
  hist(
    xbar,
    main = paste(&quot;Sample size,&quot;, i),
    col = brewer.pal(n=12, &quot;PuBu&quot;),
      #wes_palette(wes.colors[7], 4, type = &quot;continuous&quot;),
    probability = TRUE,
    las = 1, 
    xlab = paste(&quot;Mean =&quot;,round(mean(xbar), 3), sep = &quot; &quot;),
    xlim = c(70, 170),
    ylim = c(0, .2),
    ylab = &quot;&quot;
  )
}
mtext(&quot;Simple Random Sampling with Various Sizes&quot;, side = 3, line = 1, cex = 1.5, outer = TRUE)
mtext(&quot;Density&quot;, side = 2, line = 1, cex = 1, outer = TRUE)
mtext(&quot;AQI&quot;, side = 1, line = 1, cex = 1, outer = TRUE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/central-limit-theorem-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>The AQI average of the entire dataset is 114.22 and the standard deviation is 50.4. Even though the distribution of the AQI data is positively skewed we can see from the histograms below that the average of the sample means is very close to the dataset mean. Each of the distributions has a slight skew to the right, but as the sample size increases the distribution becomes close to normal, and the standard deviation decreases. These changes are in-line with the central limit theorem and show that as we take many samples, the mean starts to localize around the population mean and the standard deviation decreases.</p>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Mean</th>
<th align="center">Standard Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>Population</strong></td>
<td align="center">114.215</td>
<td align="center">50.4</td>
</tr>
<tr class="even">
<td align="center">S = 10</td>
<td align="center">114.443</td>
<td align="center">16</td>
</tr>
<tr class="odd">
<td align="center">S = 20</td>
<td align="center">114.066</td>
<td align="center">11.4</td>
</tr>
<tr class="even">
<td align="center">S = 50</td>
<td align="center">114.267</td>
<td align="center">7.4</td>
</tr>
<tr class="odd">
<td align="center">S = 500</td>
<td align="center">114.386</td>
<td align="center">2.2</td>
</tr>
</tbody>
</table>
</div>
<div id="additional-sampling-methods" class="section level2" number="2.7">
<h2 number="2.7"><span class="header-section-number">2.7</span> Additional Sampling Methods</h2>
<p>The following section utilizes different sample methods on the AQI data to demonstrate the effectiveness of sampling in determining the distribution of a population. A sample size of 500 was used for these calculations.</p>
<div id="simple-random-sampling-without-replacement" class="section level3" number="2.7.1">
<h3 number="2.7.1"><span class="header-section-number">2.7.1</span> Simple Random Sampling without Replacement</h3>
<pre class="r"><code># SRSWOR
sample.size &lt;- 500

set.seed(4099)

aqi.srswor &lt;- srswor(sample.size, nrow(cn.atmos))

aqi.srswor &lt;- cn.atmos[aqi.srswor != 0,]

par(mar = c(5,5,2,2))
hist(
  aqi.srswor$AQI,
  las = 1,
  col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
  main = &quot;SRSWOR&quot;,
  probability = TRUE,
  xlab = paste(&quot;Sample size&quot;, sample.size, sep = &quot; &quot;),
  xlim = c(0, 500),
  ylim = c(0, .015),
  breaks = 20
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/srswor-sample-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
</div>
<div id="systematic-sampling" class="section level3" number="2.7.2">
<h3 number="2.7.2"><span class="header-section-number">2.7.2</span> Systematic Sampling</h3>
<pre class="r"><code># Systematic Sampling

N &lt;- nrow(cn.atmos)
n &lt;- 500
k &lt;- (ceiling(N/n))

set.seed(4099)
r &lt;- sample(k, 1)

my.index &lt;- seq(r, by = k, length = n)

aqi.syst.samp &lt;- cn.atmos[my.index,]

par(mar = c(5, 5, 2, 2))
hist(
  aqi.syst.samp$AQI,
  las = 1,
  col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
  main = &quot;Systematic Sampling&quot;,
  probability = TRUE,
  xlab = paste(&quot;Sample size&quot;, n, sep = &quot; &quot;),
  xlim = c(0, 500),
  ylim = c(0, .02),
  breaks = 20
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/systematic-sample-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
</div>
<div id="stratified-sampling" class="section level3" number="2.7.3">
<h3 number="2.7.3"><span class="header-section-number">2.7.3</span> Stratified Sampling</h3>
<pre class="r"><code># Stratified Sampling

cn.atmos.ord &lt;- as.data.frame(cn.atmos[order(cn.atmos$aqi_level),])

# Remove &quot;Hazardous&quot; because the strata size for hazardous is equal to 0, and
# causes R to throw an error 
cn.atmos.ord &lt;- subset(cn.atmos.ord, cn.atmos.ord$aqi_level != &quot;Hazardous&quot;)
cn.atmos.ord.freq &lt;- table(cn.atmos.ord$aqi_level)

sample.size &lt;- 50

stratum.size &lt;- sample.size * cn.atmos.ord.freq / sum(cn.atmos.ord.freq)
# stratum.size &lt;- as.vector(subset(stratum.size, stratum.size != 0))

stratum.size &lt;- as.vector(round(stratum.size))

set.seed(4099)
aqi.strata &lt;- strata(
  cn.atmos.ord,
  stratanames = c(&quot;aqi_level&quot;),
  size = stratum.size,
  method = &quot;srswor&quot;,
  description = TRUE
)</code></pre>
<pre><code>## Stratum 1 
## 
## Population total and number of selected units: 23525 25 
## Stratum 2 
## 
## Population total and number of selected units: 13584 15 
## Stratum 3 
## 
## Population total and number of selected units: 7779 8 
## Stratum 4 
## 
## Population total and number of selected units: 1328 1 
## Number of strata  4 
## Total number of selected units 49</code></pre>
<pre class="r"><code>aqi.strata.sample &lt;- getdata(cn.atmos, aqi.strata)


hist(
  aqi.strata.sample$AQI,
  probability = TRUE,
  las = 1,
  col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
  xlab = paste(&quot;Sample size&quot;, sample.size, sep = &quot; &quot;),
  main = &quot;Stratified&quot;,
  xlim = c(0, 500),
  ylim = c(0, .02),
  breaks = 15
)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/stratified-sample-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
</div>
<div id="comparing" class="section level3" number="2.7.4">
<h3 number="2.7.4"><span class="header-section-number">2.7.4</span> Comparing</h3>
<pre class="r"><code># Compare the population and the three sample types

par(mfrow = c(2,2), oma = c(3,3,3,1), mar = c(2,3,1,1))
simple &lt;- hist(
  aqi.srswor$AQI,
  las = 1,
  col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
  main = &quot;SRSWOR&quot;,
  probability = TRUE,
  xlab = paste(&quot;Sample size&quot;, sample.size, sep = &quot; &quot;),
  xlim = c(0, 500),
  ylim = c(0, .02),
  breaks = 20
)
syst &lt;- hist(aqi.syst.samp$AQI,
             las = 1,
             col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
             main = &quot;Systematic Sampling&quot;,
             probability = TRUE,
             xlab = &quot;&quot;,
             ylab = &quot;&quot;,
             xlim = c(0, 500),
             ylim = c(0, .02),
             breaks = 20
)
strat &lt;- hist(aqi.strata.sample$AQI,
              probability = TRUE,
              las = 1,
              col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
              xlab = &quot;&quot;,
              ylab = &quot;&quot;,
              main = &quot;Stratified&quot;,
              xlim = c(0, 500),
              ylim = c(0, .02),
              breaks = 15
)
hist(cn.atmos$AQI,
     probability = TRUE,
     main = &quot;Population&quot;,
     ylab = &quot;&quot;,
     xlab = &quot;&quot;,
     col = rev(brewer.pal(n=16, &quot;BuPu&quot;)),
    #wes_palette(wes.colors[4], 4, type = &quot;continuous&quot;),
     las = 1,
     xlim = c(0, 500),
     ylim = c(0, .02)
     )

mtext(&quot;Distributions of Various Sampling Methods&quot;, side = 3, line = 1, cex = 1.5, outer = TRUE)
mtext(&quot;Density&quot;, side = 2, line = 1, cex = 1, outer = TRUE)
mtext(&quot;AQI&quot;, side = 1, line = 1, cex = 1, outer = TRUE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/sample-comparison-1.png" width="672" /></p>
<pre class="r"><code>par(def.par)</code></pre>
<p>Comparing the three samples with the distribution of the population reveals that the distribution for each sample follows the distribution of the population. This reinforces that sampling is a good method for exploring the data within datasets, even if the population is not available.</p>
</div>
</div>
<div id="aqi-by-wind-direction" class="section level2" number="2.8">
<h2 number="2.8"><span class="header-section-number">2.8</span> AQI by Wind Direction</h2>
<p>It is outside of the scope of this project to analyze the correlation between every variable, but one relationship that is examined is the relationship between the wind direction, wind strength, and AQI. Beijing controls pollution levels by moving pollution-producers such as factories into satellite cities and by limiting agricultural practices such as burning crop waste within a certain distance of the city center (Feng, 2018). An interesting question is does pollution from the satellite cities and from rural areas get blown into the city on strong-wind days?</p>
<p>To explore this, a library call ‘openair’ that allows for the creation of a “wind-rose” and “pollution-rose” to illustrate if a relationship exists is used.</p>
<div id="wind-rose" class="section level3" number="2.8.1">
<h3 number="2.8.1"><span class="header-section-number">2.8.1</span> Wind-Rose</h3>
<pre class="r"><code>print(wind.Fall, split = c(1, 1, 2, 2))
print(wind.Spring, split = c(2, 1, 2, 2), newpage = FALSE)
print(wind.Summer, split = c(1, 2, 2, 2), newpage = FALSE)
print(wind.Winter, split = c(2, 2, 2, 2), newpage = FALSE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/print-wind-rose-1.png" width="672" /></p>
<p>The first wind-rose shows wind-strength partnered with wind-direction, by season. Some observations are that the Winter and Fall both have strong winds coming from the NW, while the Spring has strong winds from both the NW and the SW. The Summer only has strong winds from the SW. One possible explanation for this is that in late spring the prevailing winds switch from NW to SW and then switch back during the Fall. Analysis on wind direction and speed by day would need to be done to determine if that was the actual pattern in 2017.</p>
</div>
<div id="pollution-rose" class="section level3" number="2.8.2">
<h3 number="2.8.2"><span class="header-section-number">2.8.2</span> Pollution-Rose</h3>
<pre class="r"><code>print(pol.Fall, split = c(1, 1, 2, 2))
print(pol.Spring, split = c(2, 1, 2, 2), newpage = FALSE)
print(pol.Summer, split = c(1, 2, 2, 2), newpage = FALSE)
print(pol.Winter, split = c(2, 2, 2, 2), newpage = FALSE)</code></pre>
<p><img src="CS544_FinalProject_Ascher_Rmarkdown_files/figure-html/print-pollution-rose-1.png" width="672" /></p>
<p>The pollution-rose also shows the counts of the wind-direction, but instead of indicating wind-speed by the color changes, the color-scheme indicates the levels of pollution that occurred when the wind was blowing from each direction.</p>
<p>Looking at these charts we can observe that there is the most purple in the winter and the spring. From that we can infer that hazardous AQI levels occur more frequently during those seasons. The Spring rose also shows the highest concentration of hazardous AQI observations when the wind is blowing from the SW. Correlation may exist, but it is not possible to infer if the AQI is higher during those observations because AQI was high for the whole season and the wind blew from the SW most often, or if AQI was high because the wind was blowing from the southwest and was carrying pollution into the city.</p>
</div>
</div>
</div>
<div id="conclusion" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> Conclusion</h1>
<div id="known-issues-and-recommendations" class="section level2" number="3.1">
<h2 number="3.1"><span class="header-section-number">3.1</span> Known Issues and Recommendations</h2>
<p>Data integrity in China is an unknown. A study in 2016 by Liang et al. , suggests that official AQI counts in China have a range of reliability.</p>
<p>According to Reuters (2018), PM2.5 levels for 2017 in Beijing fell by 39.6% from their 2016 values. Without data for the surrounding year, it is not possible to say if this was a trend, or an anomaly. A data-set that allows year-over-year changes should be analyzed to see if this trend continued.Overall,</p>
</div>
<div id="summary" class="section level2" number="3.2">
<h2 number="3.2"><span class="header-section-number">3.2</span> Summary</h2>
<p>Overall, this analysis has shown that in 2017 Beijing experienced mostly clear sky conditions, with haze and fog the other major weather conditions present. The observed occurrence of rain or other conditions was less than 1%. Around 53% of recorded AQI levels were in the “Moderate” range, with the other 47% being “Unhealthy for Some” or worse. AQI levels had the highest mean in the Spring, but the most extreme observations were recorded during the Winter. Sampling on the data demonstrated the validity of the Central Limit Theorem, and various sampling techniques were shown to follow the distribution of the population data. Finally, wind strength was shown to be the strongest from the NW throughout the year, with correlation to AQI levels unknown.</p>
</div>
</div>
<div id="appendix-a" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Appendix A</h1>
<p>###Project Requirements | | <strong>Example 1</strong> | <strong>Example 2</strong> | <strong>Example 3</strong> | |——————————————————————————————-|—————————|———————|:—————————————:| | Do the analysis for at least one categorical variable as in Module 3 | Weather Conditions | | | | Do the analysis for at least one numerical data as in Module 3 | AQI | Pollutants | | | Do the analysis as in Module 3 on at least one set of two+ variables | Weather &amp; Season | AQI &amp; Pollutants | AQI &amp; Sky Conditions | | Pick a variable with numerical data and examine the distribution | AQI | AQI &amp; Pollutants | | | Draw random samples of the data and compare to the central limit theory for that variable | AQI Central Limit Theorem | | | | Show how different sampling methods can be used. | SRSWOR | Systematic Sampling | Stratified Sampling | | Any feature not mentioned above. | OpenAir “windRose” | Rmarkdown | Correlation and linear regression line. |</p>
</div>
<div id="bibliography" class="section level1" number="5">
<h1 number="5"><span class="header-section-number">5</span> Bibliography</h1>
<p>AirNow.gov. (n.d.). <em>AQI Basics | AirNow.gov</em>. Retrieved March 1, 2020, from <a href="https://www.airnow.gov/aqi/aqi-basics/" class="uri">https://www.airnow.gov/aqi/aqi-basics/</a></p>
<p>Boguski, T. (2006, October). <em>Understanding Units of Measurement</em> (Issue 2). Center for Hazardous Substance Research - Kansas State University. <a href="https://cfpub.epa.gov/ncer_abstracts/index.cfm/fuseaction/display.files/fileid/14285" class="uri">https://cfpub.epa.gov/ncer_abstracts/index.cfm/fuseaction/display.files/fileid/14285</a></p>
<p>Feng, E. (2018, April 2). China moves its factories back to the countryside. <em>Financial Times</em>. <a href="https://www.ft.com/content/fe86f76c-1215-11e8-8cb6-b9ccc4c4dbbb" class="uri">https://www.ft.com/content/fe86f76c-1215-11e8-8cb6-b9ccc4c4dbbb</a></p>
<p>Liang, X., Li, S., Zhang, S., Huang, H., &amp; Chen, S. X. (2016). PM2.5data reliability, consistency, and air quality assessment in five Chinese cities. <em>Journal of Geophysical Research: Atmospheres</em>, <em>121</em>(17), 10,220-10,236. <a href="https://doi.org/10.1002/2016jd024877" class="uri">https://doi.org/10.1002/2016jd024877</a></p>
<p>Reuters Staff. (2018, February 28). CORRECTED-China’s 2017 coal consumption rose after three-year decline, clean energy portion up. <em>Reuters News</em>. <a href="https://www.reuters.com/article/china-energy-coal/corrected-chinas-2017-coal-consumption-rose-after-three-year-decline-clean-energy-portion-up-idUSL4N1QI48M" class="uri">https://www.reuters.com/article/china-energy-coal/corrected-chinas-2017-coal-consumption-rose-after-three-year-decline-clean-energy-portion-up-idUSL4N1QI48M</a></p>
<p>Teesing Enginering. (n.d.). <em>Teesing - PPM / mg/m3 converter</em>. Teesing. Retrieved February 15, 2021, from <a href="https://www.teesing.com/en/page/library/tools/ppm-mg3-converter" class="uri">https://www.teesing.com/en/page/library/tools/ppm-mg3-converter</a></p>
<p>United States Environmental Protection Agency. (2018, September). <em>Technical Assistance Document for the Reporting of Daily Air Quality – the Air Quality Index (AQI)</em>. Airnow. <a href="https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf" class="uri">https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf</a></p>
<p>University of California, Berkeley. (n.d.). <em>Glossary of Statistical Terms</em>. Berkley Stats. Retrieved March 3, 2021, from <a href="https://www.stat.berkeley.edu/~stark/SticiGui/Text/gloss.htm" class="uri">https://www.stat.berkeley.edu/~stark/SticiGui/Text/gloss.htm</a></p>
<p>Wang, H. (2019, March 27). <em>Air pollution and meteorological data in Beijing 2017-2018</em> (Version 1) <a href="#dataset">Dataset</a>. Harvard Dataverse. <a href="https://doi.org/10.7910/DVN/USXCAK" class="uri">https://doi.org/10.7910/DVN/USXCAK</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
